// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Models;

public partial class BackendExamHubContext : DbContext
{
    public BackendExamHubContext(DbContextOptions<BackendExamHubContext> options)
        : base(options)
    {
    }

    public virtual DbSet<MyofficeAcpd> MyofficeAcpds { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MyofficeAcpd>(entity =>
        {
            entity.HasKey(e => e.AcpdSid).HasName("PK__Myoffice__ACD3533E5837C0FD");

            entity.ToTable("Myoffice_ACPD");

            entity.Property(e => e.AcpdSid)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("acpd_sid");
            entity.Property(e => e.AcpdCname)
                .HasMaxLength(60)
                .HasColumnName("acpd_cname");
            entity.Property(e => e.AcpdEmail)
                .HasMaxLength(60)
                .HasColumnName("acpd_email");
            entity.Property(e => e.AcpdEname)
                .HasMaxLength(40)
                .HasColumnName("acpd_ename");
            entity.Property(e => e.AcpdLoginId)
                .HasMaxLength(30)
                .HasColumnName("acpd_LoginID");
            entity.Property(e => e.AcpdLoginPw)
                .HasMaxLength(60)
                .HasColumnName("acpd_LoginPW");
            entity.Property(e => e.AcpdMemo)
                .HasMaxLength(120)
                .HasColumnName("acpd_memo");
            entity.Property(e => e.AcpdNewid)
                .HasMaxLength(20)
                .HasColumnName("acpd_newid");
            entity.Property(e => e.AcpdNowdatetime)
                .HasColumnType("datetime")
                .HasColumnName("acpd_nowdatetime");
            entity.Property(e => e.AcpdSname)
                .HasMaxLength(40)
                .HasColumnName("acpd_sname");
            entity.Property(e => e.AcpdStatus).HasColumnName("acpd_status");
            entity.Property(e => e.AcpdStop).HasColumnName("acpd_stop");
            entity.Property(e => e.AcpdStopMemo)
                .HasMaxLength(600)
                .HasColumnName("acpd_stopMemo");
            entity.Property(e => e.AcpdUpddatetime)
                .HasColumnType("datetime")
                .HasColumnName("acpd_upddatetime");
            entity.Property(e => e.AcpdUpdid)
                .HasMaxLength(20)
                .HasColumnName("acpd_updid");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}