// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using WebApplication1.Models;

namespace WebApplication1.Models
{
    public partial interface IBackendExamHubContextProcedures
    {
        Task<List<InsertMyOfficeExecutionLogResult>> InsertMyOfficeExecutionLogAsync(string StoredPrograms, Guid? GroupID, bool? isCustomDebug, string ExecutionProgram, string ExecutionInfo, bool? VerifyNeeded, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> NEWSIDAsync(string TableName, OutputParameter<string> ReturnSID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_AddLogResult>> usp_AddLogAsync(byte? _InBox_ReadID, string _InBox_SPNAME, Guid? _InBox_GroupID, string _InBox_ExProgram, string _InBox_ActionJSON, OutputParameter<string> _OutBox_ReturnValues, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_DeleteMyofficeACPDResult>> usp_DeleteMyofficeACPDAsync(string SID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_GetMyofficeACPDResult>> usp_GetMyofficeACPDAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_InsertMyofficeACPDResult>> usp_InsertMyofficeACPDAsync(string JsonData, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_UpdateMyofficeACPDResult>> usp_UpdateMyofficeACPDAsync(string JsonData, string SID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
