// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    public partial class usp_GetMyofficeACPDResult
    {
        [Column("JSON_F52E2B61-18A1-11d1-B105-00805F49916B")]
        public string JSON_F52E2B6118A111d1B10500805F49916B { get; set; }
    }
}
